### ISSUE TITLE
Documentation clarity

### ISSUE THREAD

**Issue by Steviant-zz** [Karnith/machinepack-sailsgulpify#12]
This is going to sound like a stupid question, but I need a little help with getting this up and running. Where should I install the machinepack? I followed the instructions in a test directory but `sails new` still generates a site using grunt. Any help would be much appreciated!

**Comment by Karnith** [comment]
This machinepack gets installed after you create your project, or in an existing project that you want to change to gulp. Just npm install and call the configuration script to configure and toggle between grunt and gulp. The machinepack isn't a generator to be used with .sailsrc.

Thanks,
Karnith

Matthew Marino
JCMar
http://www.jcmar.com
mmarino@jcmar.com
P: +1 (206) 612-1725

-------- Original message --------

**Comment by Steviant-zz** [comment]
Ah, gotcha. Fantastic, thanks for your help!
