### ISSUE TITLE
This machinepack does not remove the need for grunt entirely.

### ISSUE THREAD

**Issue by netlander** [Karnith/machinepack-sailsgulpify#17]
After going through the install and setup process you'd think that the need for grunt as a dependency is removed but it seems that grunt is still needed somewhere in the deep bowels of the project.
Let me explain, after installing this plugin I went for removing grunt from package.json, I have also removed all of grunt modules in node_modules folder, deleted the tasks folder (grunt tasks) and removed gruntfile.js.
However, when I lift the project it starts seemingly ok but a quick look at the browser console reveals a couple of 404s, it looks like gulp hasn't compiled importer.less and failed to copy it and sails.io.js.
Because this is a fresh install the project doesn't contain any other assets (which wouldn't be copied either I presume).
The other strange thing which is likely the root cause of the problem, is that whereas grunt used to copy all needed public assets to .temp/public/, this new gulp setup is not doing that and I wonder where is the site being served from?

**There is a clear dependency on grunt after installing and configuring the project to use this plugin.**

**Comment by Karnith** [comment]
No, there isn't. I'll take a look, but it sounds like the less compiler isn't working. Everything should be copied to .tmp/public when it runs. Can you post the output of sails lift --verbose here for me?

The only "dependency" is the word grunt in the default hooks js and the hook folder grunt in the core.

**Comment by netlander** [comment]
I must be missing something because if I delete the .tmp/public folder and lift, gulp doesn't even create the folders so it's only serving the .ejs templates from /view.

It could be the changes you pushed three days ago...

Here's the entire lift output
`
verbose: Setting Node environment...                                                                                                                                       
verbose: In this Sails app, detected special code languages: 0 []                                                                                                          
verbose: moduleloader hook loaded successfully.                                                                                                                            
verbose: Loading app config...                                                                                                                                             
verbose: userconfig hook loaded successfully.                                                                                                                              
verbose: Exposing global variables... (you can customize/disable this by modifying the properties in`sails.config.globals`.  Set it to`false`to disable all globals.)   
verbose: Loading user hooks...                                                                                                                                             
verbose: userhooks hook loaded successfully.                                                                                                                               
verbose: Loading runtime custom response definitions...                                                                                                                    
verbose: Loading app services...                                                                                                                                           
verbose: logger hook loaded successfully.                                                                                                                                  
verbose: request hook loaded successfully.                                                                                                                                 
verbose: Loading the app's models and any custom adapters...                                                                                                               
verbose: Loading app models...                                                                                                                                             
verbose: Loading app adapters...                                                                                                                                           
verbose: Overriding ejs engine config with ejslocals to implement layout support...                                                                                        
verbose: views hook loaded successfully.                                                                                                                                   
verbose: Loading blueprint middleware...                                                                                                                                   
verbose: blueprints hook loaded successfully.                                                                                                                              
verbose: responses hook loaded successfully.                                                                                                                               
verbose: controllers hook loaded successfully.                                                                                                                             
verbose: Loading policy modules from app...                                                                                                                                
verbose: Finished loading policy middleware logic.                                                                                                                         
verbose: policies hook loaded successfully.                                                                                                                                
verbose: services hook loaded successfully.                                                                                                                                
verbose: csrf hook loaded successfully.                                                                                                                                    
verbose: cors hook loaded successfully.                                                                                                                                    
  i18n:debug will use E:\0000.src\02.web.02\sails\sails-gulp-003\config\locales\en.json +0ms                                                                               
  i18n:debug read E:\0000.src\02.web.02\sails\sails-gulp-003\config\locales\en.json for locale: en +1ms                                                                    
  i18n:debug will use E:\0000.src\02.web.02\sails\sails-gulp-003\config\locales\es.json +2ms                                                                               
  i18n:debug read E:\0000.src\02.web.02\sails\sails-gulp-003\config\locales\es.json for locale: es +0ms                                                                    
  i18n:debug will use E:\0000.src\02.web.02\sails\sails-gulp-003\config\locales\fr.json +2ms                                                                               
  i18n:debug read E:\0000.src\02.web.02\sails\sails-gulp-003\config\locales\fr.json for locale: fr +1ms                                                                    
  i18n:debug will use E:\0000.src\02.web.02\sails\sails-gulp-003\config\locales\de.json +1ms                                                                               
  i18n:debug read E:\0000.src\02.web.02\sails\sails-gulp-003\config\locales\de.json for locale: de +1ms                                                                    
verbose: i18n hook loaded successfully.                                                                                                                                    
verbose: session hook loaded successfully.                                                                                                                                 
verbose: Setting default Express view engine to ejs...                                                                                                                     
verbose: http hook loaded successfully.                                                                                                                                    
verbose: Preparing socket.io...                                                                                                                                            
verbose: sockets hook loaded successfully.                                                                                                                                 
verbose: Starting ORM...                                                                                                                                                   
verbose: orm hook loaded successfully.                                                                                                                                     
verbose: pubsub hook loaded successfully.                                                                                                                                  
verbose: Built-in hooks are ready.                                                                                                                                         
verbose: Instantiating registry...                                                                                                                                         
verbose: Loading router...                                                                                                                                                 
verbose: Policy-controller bindings complete!                                                                                                                              
verbose: All hooks were loaded successfully.                                                                                                                               
verbose: Starting app at E:\0000.src\02.web.02\sails\sails-gulp-003...                                                                                                     
verbose: Running the setup logic in`sails.config.bootstrap(cb)`...                                                                                                        
info:                                                                                                                                                                      
info:                .-..-.                                                                                                                                                
info:                                                                                                                                                                      
info:    Sails              <|    .-..-.                                                                                                                                   
info:    v0.12.3             |\                                                                                                                                            
info:                       /|.\                                                                                                                                           
info:                      / || \                                                                                                                                          
info:                    ,'  |'  \                                                                                                                                         
info:                 .-'.-==|/_--'                                                                                                                                        
info:`--'-------'  
info:    **---_**--**_---**_--**_---**_--___  
info:  ____---**_--**_---**_--**_---**_--**_-__  
info:  
info: Server lifted in `E:\0000.src\02.web.02\sails\sails-gulp-003`  
info: To see your app, visit http://localhost:1337  
info: To shut down Sails, press <CTRL> + C at any time.                                                                                                                    

debug: -------------------------------------------------------  
debug: :: Sat Apr 09 2016 21:23:35 GMT+0100 (GMT Daylight Time)                                                                                                            

debug: Environment : development  
debug: Port        : 1337  
debug: -------------------------------------------------------  
`

**Comment by Karnith** [comment]
Gulp isn't running. Did you follow the full instructions on the main page of the repo? After install you need to 

npm install machinepack-prompts

node node_modules/machinepack-sailsgulpify/templates/toggleEngine.js

And use gulpifysails and yes to full install. After that run the same command but use gulp instead of gulpifysails.

**Comment by netlander** [comment]
Started from scratch following all four steps and it seems to be working.

Although I'm pretty sure I ran the last step twice, maybe not straight in a row, it's a bit unclear in the documentation that the last step:
`node node_modules/machinepack-sailsgulpify/templates/toggleEngine.js`
needs to run twice.

Closing the issue.
Thanks
